CREATE OR REPLACE TABLE HOTEL_MODEL.N3_TOTAL_RESERVAS_HOTEL_DIA
AS
SELECT
COUNT(HOTEL.NOMBRE_HOTEL) TOTAL_RESERVAS,
HOTEL.NOMBRE_HOTEL,
RESERVAS.FECHA_RESERVA
FROM
HOTEL_MODEL.TH_RESERVAS AS RESERVAS,
HOTEL_MODEL.DIM_HOTEL AS HOTEL,
HOTEL_MODEL.DIM_HABITACION AS HABITACION
WHERE
RESERVAS.ID_HABITACION = HABITACION.ID_HABITACION AND
HABITACION.ID_HOTEL = HOTEL.ID_HOTEL
GROUP BY
HOTEL.NOMBRE_HOTEL,
RESERVAS.FECHA_RESERVA