CREATE OR REPLACE TABLE HOTEL_MODEL.N3_STATS_SEGMENTO
AS
SELECT
SEGMENTO.NOMBRE_SEGMENTO,
AVG(tarifa_noche)  MEDIA_TARIFA,
MAX(tarifa_noche)  MIN_TARIFA,
MIN(tarifa_noche)  MAX_TARIFA
FROM
`HOTEL_MODEL.TH_RESERVAS` AS RESERVAS,
`HOTEL_MODEL.DIM_CLIENTE` AS CLIENTES,
`HOTEL_MODEL.DIM_SEGMENTO` AS SEGMENTO
WHERE
RESERVAS.ID_CLIENTE = CLIENTES.ID_CLIENTE AND
CLIENTES.ID_SEGMENTO = SEGMENTO.ID_SEGMENTO
GROUP BY
SEGMENTO.NOMBRE_SEGMENTO