CREATE OR REPLACE TABLE HOTEL_MODEL.TH_RESERVAS
(
 ID_RESERVA     INT64 NOT NULL ,
 ID_HABITACION  INT64 NOT NULL ,
 ID_CANAL       INT64 NOT NULL ,
 ID_CLIENTE     INT64 NOT NULL ,
 ID_METEO       INT64 NOT NULL ,
 TOTAL_DIAS     INT64 NOT NULL ,
 TARIFA_NOCHE   INT64 NOT NULL ,
 FECHA_RESERVA  DATE NOT NULL ,
 FECHA_CHECKIN  DATE NOT NULL ,
 FECHA_CHECKOUT DATE NOT NULL
);
